<div class="form">
	<div class="left">Working Setting</div>
	<div class="sleft">1 Week : 6 Days Working</div>
	<div class="sright">2 Week : 5 Days Working</div>
</div>
<div class="body-data">
	<div class="left">
		<table id="setting-working1" class="display" width="50%" border="1">
		<thead>
		  <tr>
		    <th width="12%">Day of the Week</th>
		    <th width="8%">Shift</th>
		    <th width="10%">Strat Time</th>
		    <th width="10%">End Time</th>
		    <th width="20%" colspan="2">Meal Period</th>
		    <th width="20%" colspan="2">Rest Period 1</th>
		    <th width="20%" colspan="2">Rest Period 2</th>
		  </tr>
		</thead>
		<tbody>
		  <tr>
		    <td rowspan="3">Monday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>15:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>15:30</td>
		    <td>23:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>20:50</td>
		    <td>21:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>23:30</td>
		    <td>7:30</td>
		    <td>4:00</td>
		    <td>4:40</td>
		    <td>1:50</td>
		    <td>2:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Tuesday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>15:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>15:30</td>
		    <td>23:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>20:50</td>
		    <td>21:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>23:30</td>
		    <td>7:30</td>
		    <td>4:00</td>
		    <td>4:40</td>
		    <td>1:50</td>
		    <td>2:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Wednesday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>15:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>15:30</td>
		    <td>23:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>20:50</td>
		    <td>21:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>23:30</td>
		    <td>7:30</td>
		    <td>4:00</td>
		    <td>4:40</td>
		    <td>1:50</td>
		    <td>2:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Thursday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>15:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>15:30</td>
		    <td>23:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>20:50</td>
		    <td>21:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>23:30</td>
		    <td>7:30</td>
		    <td>4:00</td>
		    <td>4:40</td>
		    <td>1:50</td>
		    <td>2:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Friday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>15:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>15:30</td>
		    <td>23:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>20:50</td>
		    <td>21:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>23:30</td>
		    <td>7:30</td>
		    <td>4:00</td>
		    <td>4:40</td>
		    <td>1:50</td>
		    <td>2:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Saturday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>12:30</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>12:30</td>
		    <td>16:50</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>14:20</td>
		    <td>14:30</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>16:50</td>
		    <td>21:50</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>20:50</td>
		    <td>21:00</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Sunday</td>
		    <td>1</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		</tbody>
		</table>
	</div>

	<div class="right">
		<table  id="setting-working2" class="display"  width="50%" border="1">
		<thead>
		  <tr>
		    <th width="12%">Day of the Week</th>
		    <th width="8%">Shift</th>
		    <th width="10%">Strat Time</th>
		    <th width="10%">End Time</th>
		    <th width="20%" colspan="2">Meal Period</th>
		    <th width="20%" colspan="2">Rest Period 1</th>
		    <th width="20%" colspan="2">Rest Period 2</th>
		  </tr>
		</thead>
		<tbody>
		  <tr>
		    <td rowspan="3">Monday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>16:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>16:30</td>
		    <td>1:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>22:30</td>
		    <td>22:50</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Tuesday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>16:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>16:30</td>
		    <td>1:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>22:30</td>
		    <td>22:50</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Wednesday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>16:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>16:30</td>
		    <td>1:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>22:30</td>
		    <td>22:50</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Thursday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>16:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>16:30</td>
		    <td>1:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>22:30</td>
		    <td>22:50</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Friday</td>
		    <td>1</td>
		    <td>7:30</td>
		    <td>16:30</td>
		    <td>11:40</td>
		    <td>12:20</td>
		    <td>9:30</td>
		    <td>9:40</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>16:30</td>
		    <td>1:30</td>
		    <td>18:00</td>
		    <td>18:40</td>
		    <td>22:30</td>
		    <td>22:50</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Saturday</td>
		    <td>1</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td rowspan="3">Sunday</td>
		    <td>1</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>2</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>3</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		    <td>&nbsp;</td>
		  </tr>
		</tbody>
		</table>

		<button>Save</button>
	</div>

</div>
</body>
</html>